# global
name: 'xtra-b-in1k-pt'

# periodic checkpoint
periodic_checkpoint:
  save_top_k: -1
  verbose: True
  every_n_epochs: 10

# trainer
trainer:
  max_epochs: 1600
  precision: '16-mixed'
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  num_sanity_val_steps: 0

# encoder
enc:
  arch: 'vit_base'
  drop_path_rate: 0.2

# projection
proj:
  hidden_dim: 4096
  out_dim: 768
  in_bn: False
  nlayers: 2

# predictor
predictor:
  is_block_causal: True
  block_size: 4
  num_heads: 6
  depth: 8

# auto-regressive image modelling
aim:
  num_tokens: 1
  norm_pix_loss: True
  alpha: 1.0
  proj:
    hidden_dim: 6144
    in_bn: False
    nlayers: 2
    out_bias: True

# dataset
dataset:
  imagenet1k:
    use: True

train:
  batch_size: 29

val:
  batch_size: 29
