# global
name: 'xtra-b-imagenet1k'
module: classifier
pretrained: './aimos/xtra_b-in1k_pt-warmup_15-800_epochs-dpr_0.1-bs2k-12x6GPUs/epoch=799-step=490400.ckpt'
rm_pt_param:
  - 'predictor'
  - 'proj'
  - 'aim'

cls:
  mode: linear
  num_classes: 1000
  n_last_blocks: 6
  avgpool_patchtokens: False
  avgpool_layers: True

attentive_pooling:
  num_heads: 16
  num_queries: 1

# trainer
trainer:
  max_epochs: 100
  precision: 'bf16-mixed'
  gradient_clip_val: 3.0
  accumulate_grad_batches: 4
  num_sanity_val_steps: 0

# encoder
enc_arch: 'vit_base'

# optimizer
optimizer:
  adam:
    lr: 3.0e-4
    weight_decay: 0.1
  8bit: False

scheduler:
  cosine:
    warmup_start_lr: 3.0e-5
    warmup_epochs: 10
    eta_min: 1.0e-5

# dataset
dataset:
  imagenet1k:
    use: True

train:
  batch_size: 1024
  transform:
    use_timm: True
    timm:
      input_size: 256
      is_training: True
      auto_augment: 'rand-m9-mstd0.5-inc1'
      interpolation: 'bicubic'
      re_prob: 0.25
      re_mode: 'pixel'
      re_count: 1
val:
  batch_size: 1024
